import type { Platform } from "../platform/platform.ts";
import { PaperstackError } from "../errors.ts";
import { SEA_TEMPLATE } from "../build/template.ts";

export interface CreateProjectOptions {
  title: string;
  language?: "en" | "da";
  /** ISO date (YYYY-MM-DD) for document.yaml — injected so writes stay deterministic. */
  date?: string;
}

/**
 * Scaffolds a new SEA report project: document.yaml, starter sections, a
 * .gitignore that keeps generated output out of the group's repo, and a
 * .gitattributes that keeps line endings consistent across the group's
 * machines. Everything is written deterministically (stable key order,
 * trailing newlines) so the very first commit of a shared project is clean.
 */
export async function createProject(
  platform: Platform,
  dir: string,
  options: CreateProjectOptions,
): Promise<void> {
  if (await platform.fileExists(`${dir}/document.yaml`)) {
    throw new PaperstackError(
      "project-exists",
      `This folder already contains a Paperstack report. Open it instead of creating a new one.`,
      `${dir}/document.yaml exists`,
    );
  }

  const lang = options.language ?? "en";
  const da = lang === "da";
  const dateLine = options.date ? `date: "${options.date}"\n` : "";

  // JSON string escaping is valid YAML double-quote escaping.
  const documentYaml =
    `title: ${JSON.stringify(options.title)}\n` +
    `course: ""\n` +
    `institution: ""\n` +
    `authors: [] # - { name: "Full Name", student_id: "12345" }\n` +
    dateLine +
    `language: ${lang}\n` +
    `body_cap_normalsider: 40\n` +
    `sections:\n` +
    `  - { file: sections/01-introduction.md, role: body }\n` +
    `  - { file: sections/02-references.md, role: back-matter }\n`;

  const introduction = da
    ? `# Indledning\n\n[TODO: Beskriv projektet.]\n`
    : `# Introduction\n\n[TODO: Introduce the project.]\n`;
  const references = da ? `# Referencer\n` : `# References\n`;

  await platform.mkdir(`${dir}/sections`);
  await platform.mkdir(`${dir}/figures`);
  await platform.mkdir(`${dir}/diagrams`);
  await platform.writeTextFile(`${dir}/document.yaml`, documentYaml);
  await writeIfAbsent(platform, `${dir}/paperstack-template.typ`, SEA_TEMPLATE);
  // The chosen folder may not be empty (e.g. an existing group repo):
  // never overwrite files that are already there.
  await writeIfAbsent(platform, `${dir}/sections/01-introduction.md`, introduction);
  await writeIfAbsent(platform, `${dir}/sections/02-references.md`, references);
  await ensureGitignore(platform, dir);
  // Mixed Windows/macOS groups hit CRLF diff churn in week one without this.
  await writeIfAbsent(platform, `${dir}/.gitattributes`, `* text=auto\n`);
}

async function writeIfAbsent(platform: Platform, path: string, content: string): Promise<void> {
  if (!(await platform.fileExists(path))) await platform.writeTextFile(path, content);
}

/**
 * Adds the generated-files rules to .gitignore, preserving any existing one.
 * diagrams/rendered/ is deliberately NOT ignored: the renders are
 * content-hashed and deterministic, so committing them is conflict-free and
 * lets group members (and CI) build sections containing diagrams they never
 * opened in Paperstack.
 */
async function ensureGitignore(platform: Platform, dir: string): Promise<void> {
  const path = `${dir}/.gitignore`;
  const rules =
    `# Generated by Paperstack — build output is recreated on demand\n` +
    `output/\n`;
  if (!(await platform.fileExists(path))) {
    await platform.writeTextFile(path, rules);
    return;
  }
  const existing = await platform.readTextFile(path);
  if (existing.includes("output/")) return;
  await platform.writeTextFile(path, `${existing.replace(/\n*$/, "\n\n")}${rules}`);
}
