import type { Platform } from "./platform.ts";
import { PaperstackError } from "./errors.ts";

export interface CreateProjectOptions {
  title: string;
  language?: "en" | "da";
  /** ISO date (YYYY-MM-DD) for document.yaml — injected so writes stay deterministic. */
  date?: string;
}

/**
 * Scaffolds a new SEA report project: document.yaml, starter sections, and a
 * .gitignore that keeps generated output out of the group's repo. Everything
 * is written deterministically (stable key order, trailing newlines) so the
 * very first commit of a shared project is clean.
 */
export async function createProject(
  platform: Platform,
  dir: string,
  options: CreateProjectOptions,
): Promise<void> {
  if (await platform.fileExists(`${dir}/document.yaml`)) {
    throw new PaperstackError(
      "project-exists",
      `This folder already contains a Paperstack report. Open it instead of creating a new one.`,
      `${dir}/document.yaml exists`,
    );
  }

  const lang = options.language ?? "en";
  const da = lang === "da";
  const dateLine = options.date ? `date: "${options.date}"\n` : "";

  // JSON string escaping is valid YAML double-quote escaping.
  const documentYaml =
    `title: ${JSON.stringify(options.title)}\n` +
    `course: ""\n` +
    `institution: ""\n` +
    `authors: [] # - { name: "Full Name", student_id: "12345" }\n` +
    dateLine +
    `language: ${lang}\n` +
    `body_cap_normalsider: 40\n` +
    `sections:\n` +
    `  - { file: sections/01-introduction.md, role: body }\n` +
    `  - { file: sections/02-references.md, role: back-matter }\n`;

  const introduction = da
    ? `# Indledning\n\n[TODO: Beskriv projektet.]\n`
    : `# Introduction\n\n[TODO: Introduce the project.]\n`;
  const references = da ? `# Referencer\n` : `# References\n`;

  const gitignore =
    `# Generated by Paperstack — build output and rendered diagrams are recreated on demand\n` +
    `output/\n` +
    `diagrams/rendered/\n`;

  await platform.mkdir(`${dir}/sections`);
  await platform.mkdir(`${dir}/figures`);
  await platform.mkdir(`${dir}/diagrams`);
  await platform.writeTextFile(`${dir}/document.yaml`, documentYaml);
  await platform.writeTextFile(`${dir}/sections/01-introduction.md`, introduction);
  await platform.writeTextFile(`${dir}/sections/02-references.md`, references);
  await platform.writeTextFile(`${dir}/.gitignore`, gitignore);
}
